### PR TITLE
CLI intro

### PR DESCRIPTION
**Pull request by Karyum**
This pull request is ready to be fully reviewed, the structure of it in class is going to be the following:
1) Introduce the CLI (which is the WHAT?WHY? section of the README)
2) then we are going to have a code along, about the commands and some basic ones.
3) and then there is the code along's recap or summary (so they can go over what we learned)
4) and then links to learn more about the topic

### CODE REVIEW

**Review by jamiecoe — APPROVED** [review]

**Review by shiryz — COMMENTED** [review]
I suggest adding links to all the commands in the linux manual

**Comment by Karyum** [comment]
are you sure about this @shiryz  ? there are a lot of commands it can be overwhelming [look at this list](https://ss64.com/bash/)

**Comment by shiryz** [comment]
@Karyum I'm talking about each specific command, for example https://ss64.com/bash/cat.html

**Comment by Karyum** [comment]
@shiryz alright done

**Review by shiryz — APPROVED** [review]

**Pull request merged**
